In [1]:
# Import libraries for data wrangling, preprocessing and visualization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Importing libraries for building the neural network
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

C:\Users\JLipemelton\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
data = pd.read_csv("Titanic Data/train.csv")
seed = 5
np.random.seed(seed)

In [3]:
data.head()
#data.info()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
# Replace categorical variables with numerical values
cleanup_genders = { 'Sex' : { 'female':0, 'male':1 } }
data.replace(cleanup_genders, inplace=True)
data['Sex'].value_counts()

cleanup_nums = { 'Embarked': {'S':1, 'C':2, 'Q':3} }
data.replace(cleanup_nums, inplace=True)
data['Embarked'].value_counts()

avg = data['Age'].mean()
data['Age'].fillna(avg, inplace=True)
data['Embarked'].fillna(2, inplace=True)

In [5]:
# data.drop("Name", axis=1, inplace=True)
# data.drop("Ticket", axis=1, inplace=True)
# data.head()
# count = data.isna().sum()
# final_count = data.isna().sum()
# print("\nCOUNT:\n"+ str(count) + "\nFINAL COUNT\n" + str(final_count) +"\n")

In [6]:
prediction_var = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Sex']
x = data[prediction_var].values
y = data.Survived.values
length = x.shape[0]
split = .9
point = int(split*length)

x_train = x[:point]
y_train = y[:point]
x_test = x[point:]
y_test = y[point:]
inputCount = len(prediction_var)

In [7]:
model = Sequential()
model.add(Dense(100, input_dim=inputCount, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dropout(.6))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dropout(.5))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=1000, batch_size=128, verbose=0)
print("\n\n")
score=model.evaluate(x_test, y_test, batch_size=128)




90/90 [==============================] - 0s 3ms/step


In [9]:
predictions = model.predict(x_test)
predictions = [round(float(i)) for i in predictions]

In [10]:
correct=[]
for i in range(len(predictions)):
    if predictions[i] == y_test[i]:
        correct.append(1)
    else:
        correct.append(0)

#percent predicted correctly
sum(correct)/len(correct)

0.8555555555555555

In [11]:
#percent right if just guessing 0:
print(data['Survived'].sum())
1-342/890

342


0.6157303370786518

In [12]:
test = pd.read_csv("Titanic Data/test.csv")

In [13]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [14]:
# Replace categorical variables with numerical values
cleanup_genders = { 'Sex' : { 'female':0, 'male':1 } }
test.replace(cleanup_genders, inplace=True)
test['Sex'].value_counts()

cleanup_nums = { 'Embarked': {'S':1, 'C':2, 'Q':3} }
test.replace(cleanup_nums, inplace=True)
test['Embarked'].value_counts()

avg = data['Age'].mean()
test['Age'].fillna(avg, inplace=True)
test['Embarked'].fillna(2, inplace=True)
fare_avg = data['Fare'].mean()
test['Fare'].fillna(avg, inplace=True)

prediction_var = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Sex']
tester = test[prediction_var].values

In [15]:
tester[:5]

array([[ 3.    , 34.5   ,  0.    ,  0.    ,  7.8292,  3.    ,  1.    ],
       [ 3.    , 47.    ,  1.    ,  0.    ,  7.    ,  1.    ,  0.    ],
       [ 2.    , 62.    ,  0.    ,  0.    ,  9.6875,  3.    ,  1.    ],
       [ 3.    , 27.    ,  0.    ,  0.    ,  8.6625,  1.    ,  1.    ],
       [ 3.    , 22.    ,  1.    ,  1.    , 12.2875,  1.    ,  0.    ]])

In [16]:
predictions = model.predict(tester[0:])
# for i in predictions:
#     if type(i[0]) is float:
#         i[0] = 0
predictions

array([[2.17150658e-01],
       [3.10706824e-01],
       [2.04647750e-01],
       [2.32752845e-01],
       [7.61706829e-01],
       [2.38104224e-01],
       [8.37386191e-01],
       [1.73934624e-02],
       [7.99393594e-01],
       [2.84265523e-04],
       [2.23857820e-01],
       [3.97713482e-01],
       [9.99999166e-01],
       [2.53270239e-01],
       [9.99993443e-01],
       [9.98805046e-01],
       [2.60635525e-01],
       [2.50870466e-01],
       [4.01502132e-01],
       [3.89002115e-01],
       [4.76309419e-01],
       [2.99809873e-01],
       [9.99920964e-01],
       [5.66361845e-01],
       [5.21938384e-01],
       [2.06198066e-01],
       [9.99999642e-01],
       [2.43379608e-01],
       [4.73552048e-01],
       [7.06318021e-02],
       [2.71243960e-01],
       [6.77541550e-03],
       [6.35140777e-01],
       [1.40034914e-01],
       [4.56906408e-01],
       [2.67458349e-01],
       [5.91927171e-01],
       [8.39863837e-01],
       [1.91046625e-01],
       [4.60224926e-01],


In [17]:
#predictions[0].fillna(1, inplace=True)

In [19]:
for i in range(predictions.shape[0]):
    predictions[i] = round(predictions[i][0])
predictions[:]

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],

In [23]:
# test['PassengerId'][0]
predictions[0][0]

0.0

In [28]:
import csv
with open('predictions.csv', mode='w', newline='') as prediction_file:
    write = csv.writer(prediction_file, delimiter=',')
    write.writerow(['PassengerId','Survived'])
    for i in range(predictions.shape[0]):
        write.writerow([test['PassengerId'][i] , predictions[i][0]])
#         test['PassengerId'][i]
#         predictions